
<?php
use Sys\Component\ButtonComponent;
use Sys\Component\ComboboxComponent;
use Sys\Component\InputLabelComponent;

?>
<body>
    <div class="stage-center">

        <form action="/users/submit" method="POST">
            <div class="login-box">
        
            <div class="form-border">
            <h1>User Add</h1>

                    <div class="form-inputs">
                        <?=InputLabelComponent::render("Nome do Usuário",'text' ,"userName", "", ["placeholder" => "Digite aqui o nome"])?>
                        <?=InputLabelComponent::render("Sobrenome","text", "lastName", "", ["placeholder" => "Digite aqui o sobrenome"])?>
                        <?=InputLabelComponent::render("Senha","password", "password", "", ["placeholder" => "Digite aqui a senha"])?>
                    </div>

                    <div class="input-box">
                        <label for="role">Função:</label>
                        <?php
                        $roles = [
                            '0' => 'Administrador',
                            '1' => 'Usuário',
                            '2' => 'Visitante'
                        ];
                        ?>
                        <?=ComboboxComponent::render('role', $roles, '', ['id' => 'role'])?>
                    </div>
                    </div>
                    <div class="center">
                    <?=ButtonComponent::render("Enter", "btn-primary full-btn")?>
                    </div>
            </div>
            

        </form>

    </div>

</body>
<style>

</style>
<html>
