
<?php
use Sys\Component\ButtonComponent;
use Sys\Component\InputComponent;
use Sys\Component\ComboboxComponent;

?>
<body>
    <div class="stage-center">

        <form action="/users/submit" method="POST">
            <div class="login-box">
        
            <div class="form-border">
            <h1>User Add</h1>

                    <div class="form-inputs">

                        <div class="input-box">
                        <label for="role">Nome:</label>
                        <?=InputComponent::render("userName",'Nome do Usuário' ,"text", "", ["placeholder" => "digite aqui o nome"])?>
                    </div>
                        
                    <div class="input-box">
                        <label for="role">Sobrenome:</label>
                        <?=InputComponent::render("lastName","Sobrenome", "text", "", ["placeholder" => "digite aqui o sobrenome"])?>
                    </div>

                    <div class="input-box">
                        <label for="role">Senha:</label>
                        <?=InputComponent::render("password","Senha", "password", "", ["placeholder" => "digite aqui a senha"])?>
                    </div>

                    <div class="input-box">
                        <label for="role">Função:</label>
                        <?php
                        $roles = [
                            '0' => 'Administrador',
                            '1' => 'Usuário',
                            '2' => 'Visitante'
                        ];
                        ?>
                        <?=ComboboxComponent::render('role', $roles, '', ['id' => 'role'])?>
                    </div>
                    </div>
                    <div class="center">
                    <?=ButtonComponent::render("Enter", "btn-primary full-btn")?>
                    </div>
            </div>
            

        </form>

    </div>

</body>
<style>

</style>
<html>
