
<?php
use Sys\Component\ButtonComponent;
use Sys\Component\InputComponent;
use Sys\Component\ComboboxComponent;

?>
<body>
    <div class="stage-center">

        <form action="/users/submitUpdate" method="POST" enctype="multipart/form-data">
            <div class="login-box">
        
            <div class="form-border">
                    <div class="center form-inputs">
                    <div class="input-box" style="display: none;">
                        <?=InputComponent::render("id", "number", $user->id, "")?>
                    </div>
                    
                    <div class="input-box">
                        <?=InputComponent::render("userName",'Nome de Usuario', "text", $user->userName, ["placeholder" => "digite aqui o nome"])?>
                    </div>

                    <div class="input-box">
                        <?=InputComponent::render("lastName",'Sobrenome', "text", $user->lastName, ["placeholder" => "digite aqui o sobrenome"])?>
                    </div>

                    <div class="input-box">
                        <label for="role">Função:</label>
                        <?php
                        $roles = [
                            '0' => 'Administrador',
                            '1' => 'Usuário',
                            '2' => 'Visitante'
                        ];
                        ?>
                        <?=ComboboxComponent::render('role', $roles, $user->userType, ['id' => 'role'])?>
                    </div>

                    </div>
                    <div class="center">
                    <?=ButtonComponent::render("Enter", "btn-primary full-btn")?>
                    </div>
            </div>
            

        </form>

    </div>

</body>
<style>
    label{
        width: 100%;
    }

    .input-box{
        width: 100%;
        margin-bottom: 1rem;
    }
    .form-border
    {
        border: 1px solid black;

    }
    .full-btn{
        width: 80%;
    }
    .form-inputs{
        width: calc(100%-1rem);
        display: flex;
    }


</style>
<html>
