

<?php
use Sys\Component\GridComponent;
use Sys\Component\ButtonComponent;
?>

<div>
    <h1>Lista Usuarios</h1>
    <div class='flex'>
        <input type="text" placeholder="buscar" >

        <?=ButtonComponent::render("Lupa", "btn-primary full-btn")?>
        <div style="margin-left: auto;"> 

        <a href="users/add">
        <?=ButtonComponent::render("Add", "btn-success full-btn")?>
        </a>
        </div>
    </div>
    <?=GridComponent::render($users, ['idUser'=>'id', 'userName'=>'Nome do Usuario', 'lastName'=>'Sobrenome do usuario', 'userType' => 'Tipo Usuario']) ?>
</div>    
<script>
    function jsEdit(id){
        const controller = 'user'
        OpenEdit(controller, id)
    }
    function jsAdd()
    {

    }

</script>